services:
  - type: web
    name: logintec-cloud
    env: node
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

